### ISSUE TITLE
minFQ won't run - what am I doing wrong?

### ISSUE THREAD

**Issue by rubru2019** [LooseLab/minotour-docker#5]
minotour (docker) is running on localhost, 8100

When I try to run minFQ with key and port, I get an error - "failed to connect to all addresses". Any tips or suggestions?

minFQ -k 201d23868f2e9722066a15459889f1d80c894b0c -p 8100
<_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1654699347.250973082","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3217,"referenced_errors":[{"created":"@1654699347.250971952","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":165,"grpc_status":14}]}"

best regards
R

[2022-06-08T15:02:40] INFO [minFQ.minknow_connection.__init__:402] Installed minknow API Version 5.0.0.1
[2022-06-08T15:02:40] DEBUG [minknow_api.load_grpc_credentials:341] Reading ssl certificate
[2022-06-08T15:02:40] DEBUG [minknow_api.load_grpc_credentials:361] Getting local token
[2022-06-08T15:02:40] DEBUG [root.get_local_authentication_token_file:53] Unable to connect to manager on port '9502' to retrieve local auth token path
Traceback (most recent call last):
  File "/home/brug.r/Documents/virtualPythonEnv/minotour/lib/python3.8/site-packages/minknow_api/manager.py", line 51, in get_local_authentication_token_file
    return service.local_authentication_token_path().path
  File "/home/brug.r/Documents/virtualPythonEnv/minotour/lib/python3.8/site-packages/minknow_api/manager_service.py", line 1095, in local_authentication_token_path
    return run_with_retry(self._stub.local_authentication_token_path,
  File "/home/brug.r/Documents/virtualPythonEnv/minotour/lib/python3.8/site-packages/minknow_api/manager_service.py", line 85, in run_with_retry
    result = MessageWrapper(method(message, timeout=timeout), unwraps=unwraps)
  File "/home/brug.r/Documents/virtualPythonEnv/minotour/lib/python3.8/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/brug.r/Documents/virtualPythonEnv/minotour/lib/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1654714960.599588044","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3217,"referenced_errors":[{"created":"@1654714960.599587075","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":165,"grpc_status":14}]}"

**Comment by Adoni5** [comment]
Jesus, I totally missed this! I'm sorry, I'm going to pretend that I've spent a year musing on this as I have no other excuse.

This looks like a MinKNOW and `minknow-api` version mismatch. 
`minknow-api` is the python package that connects to the back end server of MinKNOW. It tries to connect on the port 9502, which is the secure GRPC port for MinKNOW. If your version of MinKNOW is too old, it may not be listening on that port. 

Just to idiot check, are you running MinKNOW on the same machine as well?
